const mockCarsData = [
    {
        brand: '',
        model: '',
        bodyType: 'Saloon',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 1999,
        imgUrl: '',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'Saloon',
        transmission: 'manual',
        price: '',
        horsePower: '',
        fuelType: 'petrol',
        mileage: '',
        year: 1999,
        imgUrl: 'http://example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'test1',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 1999,
        imgUrl: 'http://example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'Saloon',
        transmission: 'test2',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 1999,
        imgUrl: 'http://example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'Saloon',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'test3',
        mileage: 3500,
        year: 1999,
        imgUrl: 'http://example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'Saloon',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 1700,
        imgUrl: 'http://example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'Saloon',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 1999,
        imgUrl: 'example.com/car.jpg',
    },
    {
        brand: 'mercedes',
        model: 'G-wagon',
        bodyType: 'SUV',
        transmission: 'manual',
        price: 10000,
        horsePower: 450,
        fuelType: 'petrol',
        mileage: 3500,
        year: 2000,
        imgUrl: 'http://example.com/car.jpg',
    }

]


export { mockCarsData };